[package]
name = "json_to_table"
version = "0.1.0"
edition = "2021"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
repository = "https://github.com/zhiburt/tabled"
homepage = "https://github.com/zhiburt/tabled"
documentation = "https://docs.rs/json_to_table"
license = "MIT"
keywords = ["table", "print", "pretty-table", "format", "json"]
categories = ["text-processing", "visualization"]
readme = "README.md"
description = "A libary for pretty print JSON as a table"

[features]
color = ["tabled/color"]

[dependencies]
serde_json = "1.*"
tabled = { git = "https://github.com/zhiburt/tabled", rev = "883eeda030e8a822a8d5fcbee2d416b69ac4e42d" }
