[package]
name = "table_to_html"
version = "0.1.0"
edition = "2021"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
description = "The library provides a interface to convert a `tabled::Table` into a HTML table (`<table>`)."
repository = "https://github.com/zhiburt/tabled"
license = "MIT"

[dependencies]
tabled = { git = "https://github.com/zhiburt/tabled", rev = "3d86a327267da9793c5ad9b48c5d6167bc9c9314" }